"""Tests for the Laplace optimizer.

A noiseless spectrum generated by the model itself has an exact minimum at the
injected parameters, so it is the sharpest available check that the gradient
fit converges to the right place. Adding noise then checks that the error bars
the Laplace approximation reports actually bracket the truth.
"""

import numpy as np
import pytest

from taurex.differentiability import Atmosphere, LaplaceOptimizer


jax = pytest.importorskip("jax")
jnp = jax.numpy


NAMES = ("planet_radius", "T", "H2O")
# Inside the bounds each parameter declares by default, so the fit starts from
# the truth rather than from a clipped corner of the prior.
TRUTH = np.array([1.05, 950.0, np.log10(3e-4)])


@pytest.fixture
def optimizer(taurex_model, observation):
    """A Laplace optimizer set up to fit three well constrained parameters."""
    optimizer = LaplaceOptimizer(num_samples=2000, max_iterations=100)
    optimizer.set_model(taurex_model)
    optimizer.set_observed(observation)
    for name in NAMES:
        optimizer.enable_fit(name)
    return optimizer


def make_data(optimizer, taurex_model, observation, truth, noise=0.0, seed=1):
    """Replace the observation with a spectrum generated at ``truth``."""
    optimizer.update_model(truth)
    atmosphere = Atmosphere(
        taurex_model, observation, fit_params=optimizer.fitting_parameters
    )
    model = atmosphere.spectrum(jnp.asarray(truth, dtype=jnp.float64))

    data = np.asarray(model).copy()
    if noise:
        generator = np.random.default_rng(seed)
        data = data + generator.normal(0.0, noise, data.shape)
    observation._obs_spectrum[:, 1] = data
    optimizer.update_model(truth)
    return atmosphere


def test_optimizer_is_discovered_from_its_input_keyword():
    """The input file drives the optimizer through its keyword."""
    from taurex.parameter.factory import create_optimizer

    optimizer = create_optimizer({"optimizer": "laplace", "num_samples": 10})

    assert isinstance(optimizer, LaplaceOptimizer)
    assert optimizer.num_samples == 10


def test_compute_fit_requires_fitting_parameters(data_path, taurex_model, observation):
    """A fit without any free parameter is an error, not a silent no-op."""
    optimizer = LaplaceOptimizer()
    optimizer.set_model(taurex_model)
    optimizer.set_observed(observation)

    with pytest.raises(ValueError, match="No fitting parameters"):
        optimizer.compute_fit()


def test_map_recovers_injected_parameters(optimizer, taurex_model, observation):
    """The exact optimum of a noiseless spectrum is found."""
    make_data(optimizer, taurex_model, observation, TRUTH)
    optimizer.compute_fit()

    np.testing.assert_allclose(optimizer._map, TRUTH, rtol=0.0, atol=1e-4)
    assert float(
        optimizer.atmosphere.chi_squared(jnp.asarray(optimizer._map, dtype=jnp.float64))
    ) < 1e-6


def test_map_is_the_minimum(optimizer, taurex_model, observation):
    """Chi-squared does not decrease when the fit is restarted from the MAP."""
    make_data(optimizer, taurex_model, observation, TRUTH)
    optimizer.compute_fit()

    start = np.array([1.30, 850.0, -3.5])
    optimizer.update_model(start)
    optimizer.compute_fit()
    perturbed = float(
        optimizer.atmosphere.chi_squared(
            jnp.asarray(optimizer._map, dtype=jnp.float64)
        )
    )

    optimizer.update_model(TRUTH)
    best = float(
        optimizer.atmosphere.chi_squared(jnp.asarray(TRUTH, dtype=jnp.float64))
    )
    assert perturbed < best + 1e-6


def test_samples_stay_inside_the_priors(optimizer, taurex_model, observation):
    """Laplace samples never leave the bounds the input file set."""
    make_data(optimizer, taurex_model, observation, TRUTH)
    optimizer.compute_fit()

    samples = optimizer.get_samples(0)
    assert samples.shape == (optimizer.num_samples, len(NAMES))

    for index, param in enumerate(optimizer.fitting_parameters):
        low, high = param.fit_prior.boundaries()
        assert samples[:, index].min() >= min(low, high) - 1e-12
        assert samples[:, index].max() <= max(low, high) + 1e-12


def test_samples_bracket_the_truth_with_noise(optimizer, taurex_model, observation):
    """With noise the injected parameters lie within a few sigma of the MAP."""
    make_data(optimizer, taurex_model, observation, TRUTH, noise=3e-5)
    optimizer.compute_fit()

    sigma = optimizer.get_samples(0).std(axis=0)
    assert np.all(sigma > 0.0)
    assert np.all(np.isfinite(sigma))
    assert np.all(np.abs(optimizer._map - TRUTH) / sigma < 3.0)


def test_weights_are_normalised(optimizer, taurex_model, observation):
    """Sample weights form a distribution."""
    make_data(optimizer, taurex_model, observation, TRUTH)
    optimizer.compute_fit()

    weights = optimizer.get_weights(0)
    assert weights.shape == (optimizer.num_samples,)
    assert float(weights.sum()) == pytest.approx(1.0)


def test_solution_exposes_map_and_median(optimizer, taurex_model, observation):
    """The sampler interface the base optimizer consumes is implemented."""
    make_data(optimizer, taurex_model, observation, TRUTH)
    optimizer.compute_fit()

    solutions = list(optimizer.get_solution())
    assert len(solutions) == 1

    index, map_values, median_values, extra = solutions[0]
    assert index == 0
    assert extra == []
    np.testing.assert_allclose(map_values, optimizer._map)
    np.testing.assert_allclose(median_values, np.median(optimizer.get_samples(0), axis=0))


def test_reported_timings_and_counts(optimizer, taurex_model, observation):
    """The fit reports what it cost, so the two backends can be compared."""
    make_data(optimizer, taurex_model, observation, TRUTH)
    # Start away from the optimum, otherwise the fit converges on its first
    # gradient check and there is nothing to count.
    optimizer.update_model(np.array([1.30, 850.0, -3.5]))
    optimizer.compute_fit()

    assert optimizer.iterations > 0
    assert optimizer.function_evaluations > 0
    assert optimizer.gradient_evaluations > 0
    assert optimizer.compile_time > 0.0
    assert optimizer.fit_time > 0.0
    assert optimizer.laplace_time > 0.0


def test_gaussian_prior_is_used(taurex_model, observation):
    """A Gaussian prior pulls the fit towards its mean.

    A Gaussian prior makes the parameter linear, so the mixing ratio is fitted
    as a fraction rather than as its logarithm here.
    """
    from taurex.core.priors import Gaussian

    optimizer = LaplaceOptimizer(num_samples=200, max_iterations=100)
    optimizer.set_model(taurex_model)
    optimizer.set_observed(observation)
    for name in NAMES:
        optimizer.enable_fit(name)
    optimizer.set_prior("H2O", Gaussian(mean=1e-5, std=1e-6))

    truth = np.array([1.05, 950.0, 3e-4])
    make_data(optimizer, taurex_model, observation, truth)
    optimizer.compute_fit()

    # The prior is three hundred times narrower than the likelihood, so it wins.
    assert optimizer._map[2] == pytest.approx(1e-5, rel=1e-2)
